### PR TITLE
Vob 1.3.0 release

### PR DESCRIPTION
**Pull request by ltratt**
Make a 1.3.0 release: add a CHANGES file (before I forget what's been done).

### CODE REVIEW

**Comment by vext01** [comment]
LGTM. Are all of these changes backwards compatible with the last version? From the `CHANGES` file, looks so.

**Comment by vext01** [comment]
I take it you want to merge as is? No squash needed I think.

**Comment by ltratt** [comment]
Merge as-is please!

**Comment by ltratt** [comment]
Travis seemed to get stuck starting one of the jobs. I've tried starting/stopping it.

**Comment by ltratt** [comment]
OK, that worked. All tests have passed.

**Pull request merged**
