### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by thomwiggers**

### CODE REVIEW

**Comment by thomwiggers** [comment]
Is this hanging on buildbot?

**Comment by vext01** [comment]
Looks like something has glitched out. If bors has passed, then so should the buildbot-build-script.

Since @ltratt has already approved this, I'll try kicking it:
bors r+

**Comment by ltratt** [comment]
Hmm, it's still stuck. I'm not quite sure why though!

**Review by vext01 — APPROVED** [review]

**Comment by vext01** [comment]
All I did was add a review. The error reporting / logging didn't make that very clear though.

Maybe turn off required reviews?

**Comment by ltratt** [comment]
Ah, good idea! I've turned PR reviews required off.

**Pull request merged**
