### PR TITLE
Reserving space in a Vec gives a minimum, not a specific, guarantee.

### PR DESCRIPTION
**Pull request by ltratt**
Vec::reserve states:

>  Reserves capacity for at least additional more elements to be inserted in the
>  given Vec<T>. The collection may reserve more space to avoid frequent
>  reallocations.

so our previous test that we got *exactly* the size we asked for is incorrect (and, on my local machine, actually fails!). Update the tests accordingly.

### CODE REVIEW

**Review by thomwiggers — APPROVED** [review]

**Comment by thomwiggers** [comment]
It seems travis CI is not correctly communicating the status back to Github.

**Comment by vext01** [comment]
Why don't we move this to our own CI?

**Comment by ltratt** [comment]
There's a chicken-and-egg problem with this PR, as nothing else will be mergeable without this fix. I suggest we manually merge this, then I'll raise a bors/buildbot PR and then we can do the other couple of PRs. Sound like a plan?

**Comment by ltratt** [comment]
bors ping

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
OK, I think I understand what's going on now (famous last words...).

bors try

**Comment by ltratt** [comment]
Hooray! @thomwiggers If you're OK with these changes to enable bors/buildbot (which I know aren't exactly related to the original PR...), can I squash?

**Comment by thomwiggers** [comment]
That's fine, but I think you want to delete `.travis.yml`.

**Comment by ltratt** [comment]
Mea culpa! Fixed in https://github.com/softdevteam/vob/pull/50/commits/2b7efcda522ed3eb378de0976312dceff802923f. OK to squash still?

**Comment by thomwiggers** [comment]
yeah sounds good to me

**Comment by thomwiggers** [comment]
Once this is merged, will you rebase the other two?

**Comment by ltratt** [comment]
Good question. They might work as-is. I'll try them if/when this is merged.

**Pull request merged**
