### PR TITLE
Speed up binary operations by eliminating branches

### PR DESCRIPTION
**Pull request by thomwiggers**
I've benchmarked the binary operations and came to ~1250 ns per iteration.
Eliminating the branches, it's now down to ~750 ns.

### CODE REVIEW

**Comment by ltratt** [comment]
Are those numbers the wrong way around? i.e. it was 750 before and now it's 1250?

**Comment by thomwiggers** [comment]
no, I left out the time unit.

**Comment by ltratt** [comment]
OK, yes, that makes sense. I can also replicate the effect locally, so overall I like this.

I suggest that this might better be done in a single commit (though if you prefer separating them, I'm OK with that too). I think we can drop the `// Don't use short-circuiting || as it'll introduce a branch.` comments, as that's explained in the commit message.

**Comment by ltratt** [comment]
If we document every design / performance decision as a comment, we'll be overloaded :) I think correctness comments are vital, but I don't think anyone's going to think "I'll change this to `||`" without using the nice benchmarks you've provided (at which point they'll change their mind). So I think it would be good to remove these comments.

**Comment by thomwiggers** [comment]
Ok, done it.

**Comment by ltratt** [comment]
Looks good. If you squash, I can merge.

**Comment by thomwiggers** [comment]
done

**Pull request merged**
